export {
  PAGE_HEIGHT,
  PAGE_SIDE_PADDING,
  PAGE_TOP_BOTTOM_PADDING,
  PAGE_WIDTH,
  PAGE_NUMBER_FOOTER_HEIGHT,
  FIRST_PAGE_CAPACITY,
  FOLLOWING_PAGE_CAPACITY,
} from "@/features/offer-letter/constants/sheet-layout";
